query_controller_api_max_objects: 10000
generic_lookvar: "{{ query(controller_api_plugin, api_endpoint_path,
                                     query_params=awx_api_query_params,
                                     host=controller_hostname, 
                                     oauth_token=controller_oauthtoken, 
                                     verify_ssl=controller_validate_certs,
                                     return_all=true, 
                                     max_objects=query_controller_api_max_objects)
                            }}"
awx_api_query_params: {'order_by': 'organization,id'}