- name: Add and modify credentials
  awx.awx.credential:
    name:                           "{{ credential.name }}"
    description:                    "{{ credential.description | default(omit, true) }}"
    organization:                   "{{ credential.organization }}"
    credential_type:                "{{ credential.credential_type }}"
    inputs:                         "{{ credential.inputs | default(omit, true) }}"
    user:                           "{{ credential.user.username | default(omit, true) }}"
    team:                           "{{ credential.team.name | default(omit, true) }}"
    update_secrets:                 "{{ credential.update_secrets | default(omit, true) }}"
    state:                          "{{ credential.state | default(omit, true) }}"

    # Role specific options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ credentials_deltas_dict.changed_or_added }}"
  loop_control:
    loop_var: credential

- name: Remove credentials
  awx.awx.credential:
    name: "{{ credential.name }}"
    organization: "{{ credential.organization }}"
    state: "{{ credential.state }}"
    # Role specific options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ credentials_deltas_dict.removed }}"
  loop_control:
    loop_var: credential
  when: credentials_deltas_dict.removed is defined
