- name: Add and modify credential_types
  debug:
    var: credential_type
  loop: "{{ credential_types_deltas_dict.changed_or_added }}"
  loop_control:
    loop_var: credential_type
  #async: 1000
  #poll: 0
  register: credential_type_update_async

- name: "Wait for credential_type creations and modifications"
  ansible.builtin.async_status:
    jid: "{{ _job_async_result.ansible_job_id }}"
  register: credential_type_update_async_result
  until: credential_type_update_async_result.finished
  retries: 50
  delay: 10
  loop: "{{ credential_type_update_async.results }}"
  loop_control:
    loop_var: _job_async_result
  #when: _job_async_result.ansible_job_id is defined
  when: false

- name: Remove credential_types
  debug:
    var: credential_type
  loop: "{{ credential_types_deltas_dict.removed }}"
  loop_control:
    loop_var: credential_type
  when: credential_types_deltas_dict.removed is defined
  #async: 1000
  #poll: 0
  register: credential_type_removals_async

- name: "Wait for credential_type removals"
  ansible.builtin.async_status:
    jid: "{{ _job_async_result.ansible_job_id }}"
  register: credential_type_removals_async_result
  until: credential_type_removals_async_result.finished
  retries: 50
  delay: 10
  loop: "{{ credential_type_removals_async.results }}"
  loop_control:
    loop_var: _job_async_result
  #when: _job_async_result.ansible_job_id is defined
  when: false