- name: Add and modify credential_types
  awx.awx.credential_type:
    name: "{{ credential_type.name }}"
    description: "{{ credential_type.description | default(omit, true) }}"
    injectors: "{{ credential_type.injectors | default(omit, true) }}"
    inputs: "{{ credential_type.inputs | default(omit, true) }}"
    kind: "{{ credential_type.kind | default(omit, true) }}"
    state: "{{ credential_type.state | default(omit, true) }}"

    # Role specific options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ credential_types_deltas_dict.changed_or_added }}"
  loop_control:
    loop_var: credential_type

- name: Remove credential_types
  awx.awx.credential_type:
    name: "{{ credential_type.name }}"
    state: "{{ credential_type.state | default(omit, true) }}"

    # Role specific options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ credential_types_deltas_dict.removed }}"
  loop_control:
    loop_var: credential_type
  when: credential_types_deltas_dict.removed is defined
