- name: Add and modify credentials
  debug:
    var: credential
  loop: "{{ credentials_deltas_dict.changed_or_added }}"
  loop_control:
    loop_var: credential

- name: Remove credentials
  debug:
    var: credential
  loop: "{{ credentials_deltas_dict.removed }}"
  loop_control:
    loop_var: credential
  when: credentials_deltas_dict.removed is defined
