- name: Add and modify notification templates
  awx.awx.notification_template:
    name: "{{ notification_template.name }}"
    description: "{{ notification_template.description | default(omit,true) }}"
    organization: "{{ notification_template.organization }}"
    notification_type: "{{ notification_template.notification_type | default(omit,true) }}"
    notification_configuration: "{{ notification_template.notification_configuration | default(omit,true)  }}"
    messages: "{{ notification_template.messages | default(omit,true)  }}"
    state: "{{ notification_template.state | default(omit,true) }}"
    # Role Standard Options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ notification_templates_deltas_dict.changed_or_added }}"
  loop_control:
    loop_var: notification_template

- name: Remove notification templates
  awx.awx.notification_template:
    name: "{{ notification_template.name }}"
    organization: "{{ notification_template.organization }}"
    state: "{{ notification_template.state }}"
    # Role Standard Options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ notification_templates_deltas_dict.removed }}"
  loop_control:
    loop_var: notification_template
  when: notification_templates_deltas_dict.removed is defined