- name: Add and modify organizations
  awx.awx.organization:
    name: "{{ organization.name | mandatory }}"
    description: "{{ organization.description | default(omit, true) }}"
    custom_virtualenv: "{{ organization.custom_virtualenv | default(omit, true) }}"
    max_hosts: "{{ organization.max_hosts | default(omit, true) }}"
    instance_groups: "{{ organization.instance_groups | default(omit, true) }}"
    default_environment: "{{ organization.default_environment | default(omit, true) }}"
    galaxy_credentials: "{{ organization.galaxy_credentials | default(omit, true) }}"
    notification_templates_approvals: "{{ organization.notification_templates_approvals | default(omit, true) }}"
    notification_templates_started: "{{ organization.notification_templates_started | default(omit, true) }}"
    notification_templates_success: "{{ organization.notification_templates_success | default(omit, true) }}"
    notification_templates_error: "{{ organization.notification_templates_error | default(omit, true) }}"
    state: "{{ organization.state | default(omit, true) }}"
    # Role Standard Options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ organizations_deltas_dict.changed_or_added }}"
  loop_control:
    loop_var: organization

- name: Remove organizations
  awx.awx.organization:
    name: "{{ organization.name | mandatory }}"
    state: "{{ organization.state | default(omit, true) }}"
    # Role Standard Options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ organizations_deltas_dict.removed }}"
  loop_control:
    loop_var: organization
  when: organizations_deltas_dict.removed is defined

