query_controller_api_max_objects: 10000
generic_lookvar: "{{ query(controller_api_plugin, awx_api_endpoint_path,
                                     query_params=awx_api_query_params,
                                     host=controller_hostname, 
                                     oauth_token=controller_oauthtoken, 
                                     verify_ssl=controller_validate_certs,
                                     return_all=true, 
                                     max_objects=query_controller_api_max_objects)
                            }}"
awx_api_query_params: {'order_by': 'organization,id'}
controller_api_user_pass: "{{ controller_password }}"
controller_api_plugin: awx.awx.controller_api
awx_api_endpoint_path: "api/v2/{{ awx_api_endpoint_name }}/"
awx_template_filename: "endpoints/{{ awx_api_endpoint_name }}.j2"