- name: "Check if the desired state file exists"
  stat:
    path: "{{ playbook_dir }}/vars/desired_state_{{ awx_api_endpoint_name }}.yml"
  delegate_to: localhost
  register: desired_state_file_stat

- name: "Copy current state to desired state if not exists"
  copy:
    src: "{{ playbook_dir }}/vars/current_state_{{ awx_api_endpoint_name }}.yml"
    dest: "{{ playbook_dir }}/vars/desired_state_{{ awx_api_endpoint_name }}.yml"
    remote_src: true
  delegate_to: localhost
  when: not desired_state_file_stat.stat.exists

- name: "Set fact for the desired state of the desired_state_{{ awx_api_endpoint_name }}"
  set_fact:
    "desired_state_{{ awx_api_endpoint_name }}": "{{ lookup('file', path_to_file_on_controller) }}"
    cacheable: true
  vars:
    path_to_file_on_controller: "{{ playbook_dir }}/vars/desired_state_{{ awx_api_endpoint_name }}.yml"
