- name: "Fetch current {{ awx_api_endpoint_name }}"
  include_role:
    name: fetch_current_raw_state

- name: "Set fact for the current state of {{ awx_api_endpoint_name }}"
  set_fact:
    "current_state_{{ awx_api_endpoint_name }}": "{{ lookup('template', template_filename) }}"
    cacheable: true
  vars:
    template_filename: "{{ awx_api_endpoint_name }}.j2"

- name: "Save {{ awx_api_endpoint_name }} to a file on Ansible controller"
  include_tasks: save_current_state_to_disk.yml

- name: Get desired state
  include_tasks: get_desired_state_from_disk.yml

- name: "Calculate diff state list for {{ awx_api_endpoint_name }}"
  set_fact:
    "{{ awx_api_endpoint_name }}_deltas": "{{ lookup('template', 'diff.j2') | from_yaml }}"
    cacheable: true
  vars:
    current_state_fact_name: "current_state_{{ awx_api_endpoint_name }}"
    desired_state_fact_name: "desired_state_{{ awx_api_endpoint_name }}"
    state_list_before: "{{ vars[current_state_fact_name] | from_yaml | list }}"
    state_list_after: "{{ vars[desired_state_fact_name] | from_yaml | list }}"
