- name: Ensure that we have the data fetched for this awx api endpoint
  include_role:
    name: fetch_diff_between_current_and_desired_states
  vars:
    awx_api_endpoint_name: notification_templates

- name: Update notification templates
  awx.awx.notification_template:
    name: "{{ notification_template.name }}"
    description: "{{ notification_template.description | default(omit,true) }}"
    organization: "{{ notification_template.organization }}"
    notification_type: "{{ notification_template.notification_type }}"
    notification_configuration: "{{ notification_template.notification_configuration  }}"
    messages: "{{ notification_template.messages }}"
    state: "{{ notification_template.state | default(omit,true) }}"
    # Role Standard Options
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ notification_templates_deltas }}"
  loop_control:
    loop_var: notification_template
  #when: false